#!/bin/sh -e

printf 'Title: '
read title
printf 'Slug (without extension): '
read slug

year=$(date +%Y)
dir=$(date +%Y/%m)
path=$dir/$slug.md
display_date=$(date '+%B %-d, %Y')
link=$(echo "* [$title]($dir/$slug.md) <small>$display_date</small>")

mkdir -p "$dir"

cat << EOF > "$path"
$title
$(head -c "$(printf "$title" | wc -c)" /dev/zero | tr '\0' '=')
$display_date

EOF

awk '/<div class="links posts">/ { print NR } /More posts/ { print NR }' index.md | {
    read start_index
    read end_index

    awk -i inplace -v "link=$link" "NR == ($start_index + 2) { print link } NR != ($end_index - 2)" index.md
}

if ! grep -qzoP "\n$year\n----\n" posts.md; then
    awk -i inplace -v "year=$year" '/<div class="links posts">/ { print; getline; print; print year; print "----\n\n"; next } 1' posts.md
fi

awk -i inplace -v "link=$link" '!found && /^----$/ { print; getline; print; print link; found = 1; next } 1' posts.md
