ALL += hero.webp
ALL += touring/01.webp touring/02.webp touring/03.webp
ALL += mountains/01.webp mountains/02.webp mountains/03.webp mountains/04.webp mountains/05.webp mountains/06.webp mountains/07.webp mountains/08.webp mountains/09.webp mountains/10.webp mountains/11.webp mountains/12.webp mountains/13.webp mountains/14.webp mountains/15.webp mountains/16.webp mountains/17.webp mountains/18.webp mountains/19.webp mountains/20.webp mountains/21.webp
ALL += laptop/01.webp laptop/02.webp
ALL += mexico/01.webp mexico/02.webp mexico/03.webp mexico/04.webp mexico/05.webp mexico/06.webp
ALL += montreal/01.webp montreal/02.webp montreal/03.webp
ALL += toulouse/01.webp toulouse/02.webp toulouse/03.webp
ALL += andorra/01.webp andorra/02.webp andorra/03.webp andorra/04.webp andorra/05.webp andorra/06.webp andorra/07.webp andorra/08.webp andorra/09.webp
ALL += camargue/01.webp camargue/02.webp camargue/03.webp
ALL += metz-1.webp nancy-1.webp nancy-2.webp
ALL += cake/01.webp cake/02.webp cake/03.webp
ALL += nova-scotia/01.webp nova-scotia/02.webp nova-scotia/03.webp
ALL += move/01.webp move/02.webp
ALL += coffee.webp
ALL += northern-lights/01.webp northern-lights/02.webp
ALL += mountains-2024/01.webp mountains-2024/02.webp mountains-2024/03.webp mountains-2024/04.webp mountains-2024/05.webp mountains-2024/06.webp mountains-2024/07.webp mountains-2024/08.webp mountains-2024/09.webp mountains-2024/10.webp
ALL += wyoming/01.webp wyoming/02.webp wyoming/03.webp wyoming/04.webp wyoming/05.webp wyoming/06.webp wyoming/07.webp wyoming/08.webp wyoming/09.webp wyoming/10.webp
ALL += majorca/01.webp majorca/02.webp majorca/03.webp majorca/04.webp majorca/05.webp majorca/06.webp majorca/07.webp majorca/08.webp majorca/09.webp majorca/10.webp majorca/11.webp majorca/12.webp
ALL += vosges/01.webp vosges/02.webp vosges/03.webp vosges/04.webp vosges/05.webp vosges/06.webp

all: $(ALL)

clean:
	rm -f $(ALL)

hero.webp: orig/PXL_20250403_181837075~2.jpg
	magick $< -resize 1920x -gravity center -crop 1920x1080+0-200 $@

# Touring {{{

touring/01.webp: orig/PXL_20251130_194442613_exported_883_1764561874679.jpg
	magick $< -gravity center -resize x960 $@

touring/02.webp: orig/PXL_20260101_201530345.jpg
	magick $< -gravity center -resize x960 $@

touring/03.webp: orig/PXL_20260110_203236886_exported_1325_1768088530493.jpg
	magick $< -gravity center -resize x960 $@

# }}}

# Mountains {{{

mountains/01.webp: orig/PXL_20250208_223821972.jpg
	magick $< -gravity center -resize x960 $@

mountains/02.webp: orig/PXL_20250404_215912210.MP.jpg
	magick $< -gravity center -resize x960 $@

mountains/03.webp: orig/PXL_20250412_185303893.jpg
	magick $< -gravity center -resize x960 $@

mountains/04.webp: orig/PXL_20250426_175232241.jpg
	magick $< -gravity center -resize x960 $@

mountains/05.webp: orig/PXL_20250509_193256318.MP.jpg
	magick $< -gravity center -resize x960 $@

mountains/06.webp: orig/PXL_20250524_211809526.jpg
	magick $< -gravity center -resize x960 $@

mountains/07.webp: orig/PXL_20250605_013348776.jpg
	magick $< -gravity center -resize x960 $@

mountains/08.webp: orig/PXL_20250605_014331664.jpg
	magick $< -gravity center -resize x960 $@

mountains/09.webp: orig/PXL_20250607_212345760.jpg
	magick $< -gravity center -resize x960 $@

mountains/10.webp: orig/PXL_20250822_172756600.jpg
	magick $< -gravity center -resize x960 $@

mountains/11.webp: orig/PXL_20250822_174517023.jpg
	magick $< -gravity center -resize x960 $@

mountains/12.webp: orig/PXL_20250822_193027799.jpg
	magick $< -gravity center -resize x960 $@

mountains/13.webp: orig/PXL_20250822_201453215.jpg
	magick $< -gravity center -resize x960 $@

mountains/14.webp: orig/PXL_20250822_205304367.jpg
	magick $< -gravity center -resize x960 $@

mountains/15.webp: orig/PXL_20250830_184750064.jpg
	magick $< -gravity center -resize x960 $@

mountains/16.webp: orig/PXL_20250906_170009788.jpg
	magick $< -gravity center -resize x960 $@

mountains/17.webp: orig/PXL_20250906_170551384.jpg
	magick $< -gravity center -resize x960 $@

mountains/18.webp: orig/PXL_20250925_183330233.jpg
	magick $< -gravity center -resize x960 $@

mountains/19.webp: orig/PXL_20250928_160604555.jpg
	magick $< -gravity center -resize x960 $@

mountains/20.webp: orig/PXL_20251005_171632088.jpg
	magick $< -gravity center -resize x960 $@

mountains/21.webp: orig/PXL_20251013_163021987.jpg
	magick $< -gravity center -resize x960 $@

# }}}

# Laptop {{{

laptop/01.webp: orig/PXL_20250609_172015844.jpg
	magick $< -gravity center -resize x960 $@

laptop/02.webp: orig/PXL_20250609_184534242.jpg
	magick $< -gravity center -resize x960 $@

# }}}

# Mexico {{{

mexico/01.webp: orig/PXL_20250702_154415736.jpg
	magick $< -gravity center -resize x960 $@

mexico/02.webp: orig/PXL_20250702_165213657.jpg
	magick $< -gravity center -resize x960 $@

mexico/03.webp: orig/PXL_20250702_184151148.jpg
	magick $< -gravity center -resize x960 $@

mexico/04.webp: orig/PXL_20250702_211052394.MP.jpg
	magick $< -gravity center -resize x960 $@

mexico/05.webp: orig/PXL_20250703_190057548.jpg
	magick $< -gravity center -resize x960 $@

mexico/06.webp: orig/PXL_20250703_193221662.jpg
	magick $< -gravity center -resize x960 $@

# }}}

# Montreal {{{

montreal/01.webp: orig/PXL_20250704_230615364.jpg
	magick $< -gravity center -resize x960 $@

montreal/02.webp: orig/PXL_20250705_182910391.jpg
	magick $< -gravity center -resize x960 $@

montreal/03.webp: orig/PXL_20250709_161434764.jpg
	magick $< -gravity center -resize x960 $@

# }}}

# Toulouse {{{

toulouse/01.webp: orig/PXL_20250710_130533449.jpg
	magick $< -gravity center -resize x960 $@

toulouse/02.webp: orig/PXL_20250710_135333726.jpg
	magick $< -gravity center -resize x960 $@

toulouse/03.webp: orig/PXL_20250710_141113571.jpg
	magick $< -gravity center -resize x960 $@

# }}}

# Andorra {{{

andorra/01.webp: orig/PXL_20250712_104021742.MP.jpg
	magick $< -gravity center -resize x960 $@

andorra/02.webp: orig/PXL_20250713_114453115.jpg
	magick $< -gravity center -resize x960 $@

andorra/03.webp: orig/PXL_20250714_072944308.jpg
	magick $< -gravity center -resize x960 $@

andorra/04.webp: orig/PXL_20250714_091434020.jpg
	magick $< -gravity center -resize x960 $@

andorra/05.webp: orig/PXL_20250714_130114527.jpg
	magick $< -gravity center -resize x960 $@

andorra/06.webp: orig/PXL_20250715_100614527.jpg
	magick $< -gravity center -resize x960 $@

andorra/07.webp: orig/PXL_20250717_112059514.jpg
	magick $< -gravity center -resize x960 $@

andorra/08.webp: orig/PXL_20250718_100922201.MP.jpg
	magick $< -gravity center -resize x960 $@

andorra/09.webp: orig/PXL_20250720_140359468.jpg
	magick $< -gravity center -resize x960 $@

# }}}

# Camargue {{{

camargue/01.webp: orig/PXL_20250722_050554217.jpg
	magick $< -gravity center -resize x960 $@

camargue/02.webp: orig/PXL_20250722_075302031.jpg
	magick $< -gravity center -resize x960 $@

camargue/03.webp: orig/PXL_20250722_083707726.MP.jpg
	magick $< -gravity center -resize x960 $@

# }}}

# Metz & Nancy {{{

metz-1.webp: orig/PXL_20250726_121256165.jpg
	magick $< -gravity center -resize x960 $@

nancy-1.webp: orig/PXL_20250727_074525587.jpg
	magick $< -gravity center -resize x960 $@

nancy-2.webp: orig/PXL_20250728_112604590.jpg
	magick $< -gravity center -resize x960 $@

# }}}

# Cake {{{

cake/01.webp: orig/PXL_20250719_185224523.jpg
	magick $< -gravity center -resize x960 $@

cake/02.webp: orig/PXL_20250722_174102862.jpg
	magick $< -gravity center -resize x960 $@

cake/03.webp: orig/PXL_20250731_102916534.jpg
	magick $< -gravity center -resize x960 $@

# }}}

# Nova Scotia {{{

nova-scotia/01.webp: orig/PXL_20250916_101611220.jpg
	magick $< -gravity center -resize x960 $@

nova-scotia/02.webp: orig/PXL_20250916_134810285.jpg
	magick $< -gravity center -resize x960 $@

nova-scotia/03.webp: orig/PXL_20250916_162759537.jpg
	magick $< -gravity center -resize x960 $@

# }}}

# Move {{{

move/01.webp: orig/PXL_20250920_001815350.jpg
	magick $< -gravity center -resize x960 $@

move/02.webp: orig/PXL_20250920_005104339.jpg
	magick $< -gravity center -resize x960 $@

# }}}

coffee.webp: orig/PXL_20260115_165214841.PORTRAIT.jpg
	magick $< -gravity center -resize x960 $@

# Northern lights {{{

northern-lights/01.webp: orig/P2770862.jpg
	magick $< -gravity center -resize x720 $@

northern-lights/02.webp: orig/P2770879.jpg
	magick $< -gravity center -resize x720 $@

# }}}

# Mountains 2024 {{{

mountains-2024/01.webp: orig/PXL_20240620_153123601.jpg
	magick $< -gravity center -resize x960 $@

mountains-2024/02.webp: orig/PXL_20240620_165353002.jpg
	magick $< -gravity center -crop 80% +repage -resize x960 $@

mountains-2024/03.webp: orig/PXL_20240801_180632995.jpg
	magick $< -gravity center -resize x960 $@

mountains-2024/04.webp: orig/PXL_20240805_185413548.jpg
	magick $< -gravity center -resize x960 $@

mountains-2024/05.webp: orig/PXL_20240809_175531911.jpg
	magick $< -gravity center -resize x960 $@

mountains-2024/06.webp: orig/PXL_20240829_171926752.jpg
	magick $< -gravity center -resize x960 $@

mountains-2024/07.webp: orig/PXL_20240829_184154210.jpg
	magick $< -gravity center -resize x960 $@

mountains-2024/08.webp: orig/PXL_20240829_203226136.jpg
	magick $< -gravity center -resize x960 $@

mountains-2024/09.webp: orig/PXL_20240905_220445379.jpg
	magick $< -gravity center -resize x960 $@

mountains-2024/10.webp: orig/PXL_20240919_210415013.jpg
	magick $< -gravity center -resize x960 $@

# }}}

# Wyoming {{{

wyoming/01.webp: orig/PXL_20240709_221021210.jpg
	magick $< -gravity center -resize x960 $@

wyoming/02.webp: orig/PXL_20240715_185144339.jpg
	magick $< -gravity center -resize x960 $@

wyoming/03.webp: orig/PXL_20240715_195559646.jpg
	magick $< -gravity center -resize x960 $@

wyoming/04.webp: orig/PXL_20240715_215442953.jpg
	magick $< -gravity center -resize x960 $@

wyoming/05.webp: orig/PXL_20240721_164422920.jpg
	magick $< -gravity center -resize x960 $@

wyoming/06.webp: orig/PXL_20240721_185706350.jpg
	magick $< -gravity center -resize x960 $@

wyoming/07.webp: orig/PXL_20240722_193523337.jpg
	magick $< -gravity center -resize x960 $@

wyoming/08.webp: orig/PXL_20240722_203119989.jpg
	magick $< -gravity center -resize x960 $@

wyoming/09.webp: orig/PXL_20240723_192432921.jpg
	magick $< -gravity center -resize x960 $@

wyoming/10.webp: orig/PXL_20240723_201727357.jpg
	magick $< -gravity center -resize x960 $@

# }}}

# Majorca {{{

majorca/01.webp: orig/PXL_20240927_130634530.jpg
	magick $< -gravity center -resize x960 $@

majorca/02.webp: orig/PXL_20240929_142642597.jpg
	magick $< -gravity center -resize x960 $@

majorca/03.webp: orig/PXL_20240929_143445257.jpg
	magick $< -gravity center -resize x960 $@

majorca/04.webp: orig/PXL_20240930_172811441.jpg
	magick $< -gravity center -resize x960 $@

majorca/05.webp: orig/PXL_20241001_093130939.jpg
	magick $< -gravity center -resize x960 $@

majorca/06.webp: orig/PXL_20241001_122111228.jpg
	magick $< -gravity center -resize x960 $@

majorca/07.webp: orig/PXL_20241001_154610901.jpg
	magick $< -gravity center -resize x960 $@

majorca/08.webp: orig/PXL_20241001_172648399.jpg
	magick $< -gravity center -resize x960 $@

majorca/09.webp: orig/PXL_20241003_103747856.jpg
	magick $< -gravity center -resize x960 $@

majorca/10.webp: orig/PXL_20241003_104301278.jpg
	magick $< -gravity center -resize x960 $@

majorca/11.webp: orig/PXL_20241004_172212125.jpg
	magick $< -gravity center -resize x960 $@

majorca/12.webp: orig/PXL_20241011_131716530.jpg
	magick $< -gravity center -resize x960 $@

# }}}

# Vosges {{{

vosges/01.webp: orig/PXL_20241015_100633051.PORTRAIT.jpg
	magick $< -gravity center -resize x960 $@

vosges/02.webp: orig/PXL_20241016_094138932.jpg
	magick $< -gravity center -resize x960 $@

vosges/03.webp: orig/PXL_20241016_102555041.jpg
	magick $< -gravity center -resize x960 $@

vosges/04.webp: orig/PXL_20241016_112953408.jpg
	magick $< -gravity center -resize x960 $@

vosges/05.webp: orig/PXL_20241017_184049185.MP.jpg
	magick $< -gravity center -resize x960 $@

vosges/06.webp: orig/PXL_20241018_083649035.jpg
	magick $< -gravity center -resize x960 $@

# }}}
