all: arrow.png crosshair.png i-beam.png pointing-hand.png disappearing-item.png

arrow.png:
	curl -o $@ https://docs-assets.developer.apple.com/published/f33f7ae89c/arrow_2x_6e1e2a14-3ae0-4011-a745-b71327bab58e.png

crosshair.png:
	curl -o $@ https://docs-assets.developer.apple.com/published/f33f7ae89c/crosshairCursor_2x_2x_01d6c282-bd30-47c4-beea-709ad3272b4f.png

i-beam.png:
	curl -o $@ https://docs-assets.developer.apple.com/published/f33f7ae89c/IBeamCursor_2x_2x_930c79ff-a01f-437b-b797-c0be46242394.png

pointing-hand.png:
	curl -o $@ https://docs-assets.developer.apple.com/published/f33f7ae89c/pointingHandCursor_2x_2x_35c39e52-b154-4fa4-a38b-b90010739c55.png

disappearing-item.png:
	curl -o $@ https://docs-assets.developer.apple.com/published/f33f7ae89c/disappearingItemCursor_2x_2x_787c7c3c-e632-4da8-8de5-a983370dceac.png
