#!/usr/bin/env node

const fs = require('fs')
const escape = require('escape-html')

const base = process.argv[2]

process.stdout.write(fs.readFileSync('/dev/stdin', 'utf8').replace(/(href|src)="([^"]*)"/g, (match, attr, path) => {
  if (path.startsWith('https://') || path.startsWith('http://')) {
    return match
  }

  return `${attr}="${escape(new URL(path, base))}"`
}))
