#!/bin/sh -e

light=$1; shift
dark=$1; shift

cat "$light"

echo "@media (prefers-color-scheme:dark) {"
cat "$dark"
echo "}"

# Expected CSS is unmified and has only one class per line, prefix all classes with `.dark`
cat "$dark" | sed 's/^\.hljs/.dark .hljs/'
