#!/bin/sh -e

date=$(date -u +%Y-%m-%dT%H:%M:%SZ)

cat feed.xml | sed "s,<updated />,<updated>$date</updated>,;\$d"

sed -n 's,^<li><a href=",,p' dist/posts.html | head -20 | sed 's/".*//' | while read path; do
    title=$(sed -n '/^ *<title>/{p;q;}' "dist/$path" | sed 's/^ *//')
    date=$(sed -n '/^ *<p class="date">/{s/[^>]*>//;s/<.*//;p;q;}' "dist/$path")
    iso=$(node -p 'new Date(process.argv[1]).toISOString()' "$date")
    url=https://www.codejam.info/$path

    printf "  <entry>
    $title
    <link href=\"$url\" />
    <id>$url</id>
    <updated>$iso</updated>
    <content type=\"html\"><![CDATA["

    sed -n '/<\/header>/,/<footer>/p' "dist/$path" | sed '1,2d;$d' | sed '$d' | ./scripts/absolutify "$url"
    printf "]]></content>\n  </entry>\n"
done

tail -1 feed.xml
