#!/bin/sh -e
#
# Ensures that date and title match between actual articles and
# `index.md` and `posts.md` listings.
#

process() {
    file=$1; shift
    passthrough=false

    cat "$file" | while IFS= read line; do
        if "$passthrough"; then
            echo "$line"
            continue
        fi

        if [ "$line" = "## Pages" ]; then
            passthrough=true
        fi

        if ! echo "$line" | grep -q '^* .*</small>$'; then
            echo "$line"
            continue
        fi

        path=$(echo "$line" | sed 's/^.*](//;s/).*//')

        if ! [ -f "$path" ]; then
            echo "$line"
            continue
        fi

        head=$(grep -A4 '^# ' "$path")
        title=$(echo "$head" | head -1 | sed 's/^# //')
        date=$(echo "$head" | grep -B1 '^$' | head -1)
        expected="* [$title]($path) <small>$date</small>"

        if [ "$line" != "$expected" ]; then
            echo "Mismatch in $file" >&2
            echo "  Actual: $line" >&2
            echo "  Expected: $expected" >&2
            echo "  Fixing..." >&2
        fi

        echo "$expected"
    done > "$file.new"

    mv "$file.new" "$file"
}

process index.md
process posts.md
