#!/bin/sh -e

printf 'Title: '
read title

suggested_slug=$(node -p "require('@sindresorhus/slugify')(process.argv[1], { decamelize: false })" "$title")
printf "Slug [$suggested_slug]: "
read slug
slug=${slug:-$suggested_slug}

year=$(date +%Y)
dir=$(date +%Y/%m)
path=$dir/$slug.md
display_date=$(date '+%B %-d, %Y')
link=$(echo "* [$title]($dir/$slug.md) <small>$display_date</small>")

mkdir -p "$dir"

cat << EOF > "$path"
# $title
$display_date

EOF

echo "$path"

awk '/<div class="links posts">/ { print NR } /All the posts/ { print NR }' index.md | {
    read start_index
    read end_index

    awk -v "link=$link" "NR == ($start_index + 2) { print link } NR != ($end_index - 2)" index.md > index.md.new
    mv index.md.new index.md
}

if ! grep -q "^## $year$" posts.md; then
    awk -v "year=$year" '/<div class="links posts">/ { print; getline; print; print "## " year; print "\n"; next } 1' posts.md > posts.md.new
    mv posts.md.new posts.md
fi

awk -v "link=$link" '!found && /^## / { print; getline; print; print link; found = 1; next } 1' posts.md > posts.md.new
mv posts.md.new posts.md
