#!/usr/bin/env node

const path = require('path')
const fs = require('fs')
const mdit = require('markdown-it')
const escape = require('escape-html')
const slugify = require('@sindresorhus/slugify')
const hljsOrig = require('highlight.js')
const hljsCodeDiff = require('highlightjs-code-diff')

const baseUrl = 'https://www.codejam.info/'
const siteName = 'CodeJam'
const meta = {}

const file = process.argv[2]
const head = fs.readFileSync(path.resolve(__dirname, '../head.html'), 'utf8')
const foot = fs.readFileSync(path.resolve(__dirname, '../foot.html'), 'utf8')
const markdown = fs.readFileSync(file, 'utf8')
const env = {}
let layout = file.match(/^\d{4}\//) ? 'post' : 'page'

const md = mdit({
  html: true,
  typographer: true
})

const hljs = hljsCodeDiff(hljsOrig)

md.use(require('markdown-it-front-matter'), metaString => {
  for (const line of metaString.split('\n')) {
    const [key, value] = line.split(': ')
    meta[key] = value
  }

  if (meta.layout) {
    layout = meta.layout
  }
})

md.use(require('markdown-it-anchor'), {
  level: 2, // Do not permalink `<h1>`.
  slugify: slug => slugify(slug, { decamelize: false }),
  permalink: require('markdown-it-anchor').permalink.headerLink({ safariReaderFix: true })
})

md.use(require('markdown-it-deflist'))
md.use(require('markdown-it-footnote'))
md.use(require('markdown-it-highlightjs'), { hljs, auto: false })
md.use(require('markdown-it-title'), { excerpt: 3 })
md.use(require('markdown-it-attr-typographer'), { html: true })

// Strip HTML comments from output.
md.core.ruler.push('stripComments', state => {
  state.tokens = state.tokens.filter(token =>
    !(token.type === 'html_block' && token.content.trim().startsWith('<!--'))
  )

  for (const blockToken of state.tokens) {
    if (blockToken.type === 'inline' && blockToken.children) {
      blockToken.children = blockToken.children.filter((token, i, arr) => {
        if (token.type === 'html_inline' && token.content.startsWith('<!--')) {
          const prev = arr[i - 1]
          if (prev && prev.type === 'text') {
            prev.content = prev.content.replace(/\s+$/, '')
          }

          return false
        }

        return true
      })
    }
  }
})

// Rewrite local Markdown links to HTML.
md.core.ruler.push('markdownLinkRewrite', state => {
  for (const blockToken of state.tokens) {
    if (blockToken.type !== 'inline') {
      continue
    }

    for (const token of blockToken.children) {
      if (token.type !== 'link_open') {
        continue
      }

      const href = token.attrGet('href')

      if (href.includes('://')) {
        continue
      }

      token.attrSet('href', href.replace(/\.md(#|$)/, '.html$1'))
    }
  }
})

function preProcessMarkdown (markdown) {
  const h1Index = markdown.search(/^# /m)
  const frontMatter = markdown.slice(0, h1Index)
  const contentIndex = markdown.indexOf('\n\n', h1Index)
  const header = markdown.slice(h1Index, contentIndex).replace(/ {2}$/gm, '\n\n')
  const content = markdown.slice(contentIndex)

  return { frontMatter, header, content }
}

const preprocessed = preProcessMarkdown(markdown)

function postProcessHeader (header) {
  header = header
    .replace(/<h1>([^<]*) <small>/, '<h1 class="has-subtitle"><span>$1</span> <small>')

  const pCount = (header.match(/<p>/g) || []).length
  let i = 0

  env.paragraphsAfterTitle = []

  const expectDate = ['post', 'now'].includes(layout) || meta.dated

  header = header.replace(/<p>/g, () => {
    i += 1

    if (i === pCount && expectDate) {
      env.paragraphsAfterTitle.push('date')
      return '<p class="date">'
    }

    env.paragraphsAfterTitle.push('tagline')
    return '<p class="tagline">'
  })

  if (layout === 'now') {
    header += '\n<p class="tagline">This is a <a href="https://nownownow.com/about">now page</a></p>'
  }

  return header
}

md.render(preprocessed.frontMatter, env)

const header = postProcessHeader(md.render(preprocessed.header, env).trim())
const content = md.render(preprocessed.content, env).trim()

let pageTitle

if (['index.md', 'val.md'].includes(file)) {
  pageTitle = meta.excerpt ? `${env.title} - ${meta.excerpt.replace(/\.$/, '')}` : env.title
} else {
  pageTitle = `${env.title} | ${siteName}`
}

let metaTags = ''

const favicon = meta.favicon
  ? new URL(meta.favicon, `${baseUrl}${file}`).pathname
  : '/favicon.ico'

metaTags += `  <link rel="icon" href="${escape(favicon)}">\n`

if (meta.canonical) {
  metaTags += `  <link rel="canonical" href="${escape(meta.canonical)}">\n`
}

metaTags += `  <meta property="og:title" content="${escape(pageTitle)}">\n`
metaTags += `  <meta property="og:site_name" content="${siteName}">\n`

if (meta.excerpt) {
  metaTags += `  <meta property="og:description" content="${escape(md.typographer(meta.excerpt))}">\n`
} else if (env.excerpt) {
  const taglineIndex = env.paragraphsAfterTitle.indexOf('tagline')
  const tagline = taglineIndex !== -1 ? env.excerpt[taglineIndex] : null
  const excerpt = env.excerpt[env.paragraphsAfterTitle.length]
  const description = (tagline ? `${tagline}.`.replace(/\.\.?$/, '. ') : '') + excerpt
  metaTags += `  <meta property="og:description" content="${escape(description)}">\n`
}

const image = meta.image || meta.hero

if (image) {
  const absoluteImage = new URL(image, `${baseUrl}${file}`).href

  metaTags += `  <meta property="og:image" content="${escape(absoluteImage)}">\n`
} else {
  metaTags += `  <meta property="og:image" content="${escape(`${baseUrl}img/profile.jpg`)}">\n`
}

metaTags += `  <meta name="twitter:card" content="${image ? 'summary_large_image' : 'summary'}">
  <meta name="twitter:site" content="@valeriangalliat">
  <meta name="twitter:creator" content="@valeriangalliat">
`

let hero = '<header>'
let heroCredit = '</header>'

if (meta.hero) {
  const focus = meta.focus ? `; background-position: ${meta.focus}` : ''
  hero = `<header class="hero" style="background-image: url(${meta.hero})${focus}">`
}

if (meta.heroCredit) {
  heroCredit = `  <a class="hero-credit" href="${escape(meta.heroCreditUrl)}">Picture credit: ${meta.heroCredit}</a>\n  </header>`
}

let lang = ''

if (meta.lang) {
  lang = ` lang="${meta.lang}"`
}

process.stdout.write(
  head
    .replace('<title>', `<title>${escape(pageTitle)}`)
    .replace('</head>', `${metaTags}</head>`)
    .replace('<body>', layout ? `<body class="${layout}">` : '<body>')
    .replace('<header>', hero)
    .replace('</header>', heroCredit)
    .replace('<div class="content">', `<div class="content">\n${header}`)
    .replace(/<div class="content">/g, `<div class="content"${lang}>`)
)

process.stdout.write(content)
process.stdout.write('\n')

if (layout === 'post') {
  process.stdout.write('<section class="post-footer">\n  <h3>Want to leave a comment?</h3>\n')
  process.stdout.write('  <p>\n')

  if (meta.tweet) {
    process.stdout.write(`    Join the discussion on <a href="${escape(meta.tweet)}">X</a> or send me an <a href="mailto:val@codejam.info">email</a>! 💌<br>\n`)
  } else {
    process.stdout.write('    Start a conversation on <a href="https://x.com/valeriangalliat">X</a> or send me an <a href="mailto:val@codejam.info">email</a>! 💌<br>\n')
  }

  process.stdout.write('    This post helped you? <a href="https://ko-fi.com/funkyval">Buy me a coffee</a>! 🍻\n')
  process.stdout.write('  </p>\n')
  process.stdout.write('</section>\n')
}

process.stdout.write(
  foot
    .replace('https://github.com/valeriangalliat/blog', `https://github.com/valeriangalliat/blog/tree/master/${file}`)
)
