#!/usr/bin/env node

//
// Render given partial HTML file with layout.
//
// * Page title can be set in a `<title>` tag in the first line.
// * Layout name is given as first argument.
//

import concat from 'stream-concat-promise'
import fs from 'fs'
import jade from 'jade'
import * as util from './util'

const file = process.argv[2]
const base = util.base(file)
const layout = util.layout(file)

const render = locals =>
  jade.renderFile(__dirname + `/../views/${layout}.jade`, locals)

const findTitle = html => {
  const match = html.match(/^<title>(.*)<\/title>/)

  return !match
    ? ['', html]
    : [match[1], html.substr(match[0].length)]
}

concat(fs.createReadStream(file), { encoding: 'string' })
  .then(findTitle)
  .then(([title, html]) => render({ file, base, layout, title, html }))
  .then(console.log)
  .then(null, require('promise-done'))
